function [Y,E3] = YPROM(E0,E5,Y0,Y5,OTN,KOTR,AN,AK)
%
global DW Z IR ALFA FR FA
OTNF=FA/FR;
OTNOSCH=FA/(IR*Z*DW^2);
E1=(E0(KOTR)-E0(KOTR-1))/(OTN(KOTR)-OTN(KOTR-1));
E1=E0(KOTR-1)+E1*(OTNOSCH-OTN(KOTR-1));
E2=(E5(KOTR)-E5(KOTR-1))/(OTN(KOTR)-OTN(KOTR-1));
E2=E5(KOTR-1)+E2*(OTNOSCH-OTN(KOTR-1));
E3=(E2-E1)/(AK-AN);
E3=E1+E3*(AK-ALFA);
Y=0;
if OTNF > E3
    YN=(Y5(KOTR-1)-Y0(KOTR-1))/(AK-AN);
	YN=Y0(KOTR-1)+YN*(AK-ALFA);
	YV=(Y5(KOTR)-Y0(KOTR))/(AK-AN);
	YV=Y0(KOTR)+YV*(AK-ALFA);
    Y=(YV-YN)/(AK-AN);
	Y=YN+Y*(AK-ALFA);
end
end

